name: Deploy to WordPress.org

on:
  release:
    types:
      - released

jobs:
  release:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: WordPress plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: performance-lab
      - name: Upload release assets
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/${{ github.event.repository.name }}.zip
