name: Pull Request Validation

on:
  pull_request:
    branches:
      - trunk
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - edited

env:
  PR_LABELS: ${{ join( github.event.pull_request.labels.*.name, ' ' ) }}

jobs:
  check-type-label:
    name: Check [Type] Label
    runs-on: ubuntu-latest
    steps:
      - run: |
          [[ "$PR_LABELS" == *"[Type]"* ]] || exit 1
  check-focus-label:
    name: Check [Focus] Label
    runs-on: ubuntu-latest
    steps:
      - run: |
          [[ "$PR_LABELS" == *"[Focus]"* ]] || exit 1
  check-milestone:
    name: Check Milestone
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.milestone == null
        run: |
          [[ "$PR_LABELS" == *"no milestone"* ]] || exit 1
